libr/main/models.py
from libr import db


# Association table for books and authors
books_autors = db.Table('books_autors',
	db.Column('book_id', db.Integer, db.ForeignKey('books.id')),
	db.Column('author_id', db.Integer, db.ForeignKey('authors.id'))
	)


class Author(db.Model):
	"""Author entry model."""

	__tablename__='authors'
	id = db.Column(db.Integer, primary_key=True)
	name = db.Column(db.String(64), unique=True)
	books = db.relationship('Book',
							secondary=books_autors,
							backref=db.backref('authors', lazy='joined'),
							lazy='joined')


class Book(db.Model):
	"""Book entry model."""

	__tablename__='books'
	id = db.Column(db.Integer, primary_key=True)
	title = db.Column(db.String(64), unique=True)

libr/main/forms.py
from flask.ext.wtf import Form
from wtforms import StringField, SubmitField, HiddenField, ValidationError
from wtforms.ext.sqlalchemy.fields import QuerySelectMultipleField
from wtforms.validators import Required, Length, Regexp

from .models import Book, Author


def all_books():
	"""Returns books query."""
	return Book.query


def all_authors():
	"""Returns authors query."""
	return Author.query


class BookEditForm(Form):
	"""Form for adding and editing book entries."""
	title = StringField('Book title', validators=[Required(), Length(1, 64), 
			Regexp('^[^<>]+$',
			0, 'Book title must not have "<" or ">" charachters')])
	authors = QuerySelectMultipleField('Add Author(s)', 
										query_factory=all_authors, 
										get_label='name')
	submit = SubmitField('Save')

	def validate_title(self, field):
		"""Validates if book title starts with a capital letter."""
		if not field.data[0].isalpha() or \
				field.data[0].lower() == field.data[0]:
			raise ValidationError('Title must begin with capital letter.')


class AuthorEditForm(Form):
	"""Form for adding and editing author entries."""
	name = StringField('Author', validators=[Required(), Length(2, 64), 
			Regexp('^[^<>]+$', 
			0, 'Author name must not have "<" or ">" charachters')])
	books = QuerySelectMultipleField('Add Book(s)', 
									query_factory=all_books, 
									get_label='title')
	submit = SubmitField('Save')

	def validate_name(self, field):
		"""Validates if author name starts with a capital letter."""
		if not field.data[0].isalpha() or \
				field.data[0].lower() == field.data[0]:
			raise ValidationError('Author name must begin with capital letter.')


class DeleteForm(Form):
	"""Form for deleting entries."""
	id = HiddenField()
		

libr/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, models, errors

libr/main/views.py
from flask import abort, render_template, redirect, url_for, request, flash
from flask.ext.login import login_required

from libr import db
from . import main
from .models import Author, Book
from .forms import BookEditForm, AuthorEditForm, DeleteForm


@main.route('/authors')
def authors():
	"""Return page with list of all authors."""
	authors = Author.query.all()
	del_form = DeleteForm()
	return render_template('main/authors.html', authors=authors, form=del_form)


@main.route('/')
def books():
	"""Return page with list of all books."""
	books = Book.query.all()
	del_form = DeleteForm()
	return render_template('main/books.html', books=books, form=del_form)


@main.route('/author/detail/<int:id>')
def author_detail(id):
	"""Single author entry view.

	Return page with detailed information about author 
	with Author ID equal to parameter 'id' or 404 error if such
	Author ID does not exist.
	"""
	author = Author.query.get_or_404(id)
	form = DeleteForm()
	return render_template('main/author_detail.html', author=author, form=form)


@main.route('/book/detail/<int:id>')
def book_detail(id):
	"""Single book entry view.

	Return page with detailed information about book 
	with Book ID equal to parameter 'id' or 404 error if such
	Book ID does not exist.
	"""
	book = Book.query.get_or_404(id)
	form = DeleteForm()
	return render_template('main/book_detail.html', book=book, form=form)


@main.route('/book/add', methods=['POST', 'GET'])
@login_required
def add_book():
	"""Adds new book entry to the database. 
	
	Requires user authentication.
	"""
	form = BookEditForm()
	if form.validate_on_submit():
		book = Book(title=form.title.data)
		if form.authors.data:
			book.authors.extend(form.authors.data)
		db.session.add(book)
		db.session.commit()
		flash("Book entry successfully added.")
		if request.args.get('next'):
			return redirect(request.args.get('next'))
		return redirect(url_for('main.books'))
	return render_template('main/add_book.html', form=form)


@main.route('/author/add', methods=['POST', 'GET'])
@login_required
def add_author():
	"""Adds new author entry to the database. 
	
	Requires user authentication.
	"""
	form = AuthorEditForm()
	if form.validate_on_submit():
		author = Author(name=form.name.data)
		if form.books.data:
			author.books.extend(form.books.data)
		db.session.add(author)
		db.session.commit()
		flash("Author entry was successfully added.")
		if request.args.get('next'):
			return redirect(request.args.get('next'))
		return redirect(url_for('main.authors'))
	return render_template('main/add_author.html', form=form)


@main.route('/book/<int:id>', methods=['POST', 'GET'])
@login_required
def edit_book(id):
	"""Edits book entry. 
	
	Requires user authentication. Returns 404 error if Book ID does
	not exist.
	"""
	book = Book.query.get_or_404(id)
	form = BookEditForm(obj=book)
	if form.validate_on_submit():
		book.title = form.title.data
		book.authors = []
		if form.authors.data:
			book.authors.extend(form.authors.data)
		db.session.commit()
		flash("Book entry was successfully edited.")
		return redirect(url_for('main.books'))
	return render_template('main/edit_book.html', form=form, book=book)


@main.route('/author/<int:id>', methods=['POST', 'GET'])
@login_required
def edit_author(id):
	"""Edits author entry. 
	
	Requires user authentication. Returns 404 error if Author ID does
	not exist.
	"""
	author = Author.query.get_or_404(id)
	form = AuthorEditForm(obj=author)
	if form.validate_on_submit():
		author.name = form.name.data
		author.books = []
		if form.books.data:
			author.books.extend(form.books.data)
		db.session.commit()
		flash("Author entry was successfully edited.")
		return redirect(url_for('main.authors'))
	return render_template('main/edit_author.html', form=form, author=author)


@main.route('/delete/author' , methods=['POST'])
@login_required
def delete_author():
	"""Deletes author entry. 
	
	Requires user authentication and only POST requests. Returns 404 error 
	if Author ID does not exist.
	"""
	form = DeleteForm()
	id = form.id.data
	if id:
		author = Author.query.get_or_404(id)
		db.session.delete(author)
		db.session.commit()
		flash("Author entry was successfully deleted.")
		return redirect(url_for('main.authors'))
	abort(404)


@main.route('/delete/book' , methods=['POST'])
@login_required
def delete_book():
	"""Deletes book entry. 
	
	Requires user authentication and only POST requests. Returns 404 error 
	if Book ID does not exist.
	"""
	form = DeleteForm()
	id = form.id.data
	if id:
		book = Book.query.get_or_404(id)
		db.session.delete(book)
		db.session.commit()
		flash("Book entry was successfully deleted.")
		return redirect(url_for('main.books'))
	abort(404)


@main.route('/search/book')
def search_book():
	"""Book entry search.

	Takes 'match' argument from request and return list of books that matched.
	Checks match for book title and authors names fields.
	"""
	match = request.args.get('match')
	match = '%{}%'.format(match)
	books = Book.query.filter(Book.authors.any(Author.name.like(match)) + Book.title.like(match))
	return render_template('main/book-search-results.html', books=books)


@main.route('/search/author')
def search_author():
	"""Author entry search.

	Takes 'match' argument from request and return list of authors that matched.
	Checks match for author name fiels.
	"""
	match = request.args.get('match')
	match = '%{}%'.format(match)
	authors = Author.query.filter(Author.name.like(match))
	return render_template('main/author-search-results.html', authors=authors)

libr/templates/main/add_author.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}Add Author{% endblock %}
{% block main_content %}
<div class="container">
	<div class="page-header">
		<h1>Add Author</h1>
	</div>
	<div class="col-md-4">
		{{ wtf.quick_form(form) }}
	</div>
	<a href="{{ url_for('main.add_book', next=url_for('main.add_author')) }}" class="btn add-object"><span class="glyphicon glyphicon-plus"></span> Add Book</a>
</div>
{% endblock %}

libr/templates/main/add_book.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}Add Book{% endblock %}
{% block main_content %}
<div class="container">
	<div class="page-header">
		<h1>Add Book</h1>
	</div>
	<div class="col-md-4">
		{{ wtf.quick_form(form) }}
	</div>
	<a href="{{ url_for('main.add_author', next=url_for('main.add_book')) }}" class="btn add-object"><span class="glyphicon glyphicon-plus"></span> Add Author</a>
</div>
{% endblock %}

libr/templates/main/author-search-results.html
{% if authors %}
	<table class="table">
		<thead>
			<tr>
				<th>Author ID</th>
				<th>Name</th>
			</tr>
		</thead>
		<tbody>
			{% for author in authors %}
				<tr>
					<td>{{ author.id }}</td>
					<td><a href="{{ url_for('main.author_detail', id=author.id) }}">{{ author.name }}</a></td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% else %}
	<h3 class="search-not-found">Can't find anything.</h3>
{% endif %}

libr/templates/main/author_detail.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}Author Detail{% endblock %}
{% block main_content %}
<div class="container">
	<div class="page-header">
		<h1>About author - {{ author.name }}</h1>
	</div>
	<p>
		<b>Author ID:</b> {{ author.id }}
	</p>
	<p>
		<b>Name:</b> "{{ author.name }}"
	</p>
	<p><b>Books:</b></p>

	{% if author.books %}
		<ul>
			{% for book in author.books %}
					<li><a href="{{ url_for('main.book_detail', id=book.id) }}">{{ book.title }}</a></li>
			{% endfor %}
		</ul>
	{% else %}
		<h2>Sorry, we don't have any books by {{ author.name }}</h2>
	{% endif %}
	{% if current_user.is_authenticated() %}
	<p>
	<a href="{{ url_for('main.edit_author', id=author.id) }}" class="btn btn-primary">Edit Author</a>
	</p>
	<form action="{{ url_for('main.delete_author') }}" method="POST">
		{{ form.id(value=author.id) }}
		<input type="submit" class="btn btn-danger pull-right" value="Delete Author" />
	</form>
	{% endif %}
</div>
{% endblock %}

libr/templates/main/authors.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}Authors{% endblock %}
{% block main_content %}
<div class="container">
	<div class="page-header">
		<h1>Authors</h1>
	</div>
	<div class="pull-left">
		<label class="label label-info" for="search-input">Input part of author's name</label>
    	<input type="text" class="input-medium search-query" id="search-input">
    	<div class="btn btn-success" id="search-button">Find Author</div>
    	<div id="back-div"></div>
	</div>
	{% if current_user.is_authenticated() %}
	<a href="{{ url_for('main.add_author') }}" class="pull-right btn btn-warning">Add new author entry</a>
	{% endif %}
	<div class="result-table clearfix">
		{% if authors %}
		<table class="table">
			<thead>
				<tr>
				<th>Author ID</th>
				<th>Name</th>
				<th>More</th>
				</tr>
			</thead>
			<tbody>
				{% for author in authors %}
					<tr>
						<td>{{ author.id }}</td>
						<td>{{ author.name }}</td>
						<td>
							<a href="{{ url_for('main.author_detail', id=author.id) }}" class="btn btn-info">About Author</a>
							{% if current_user.is_authenticated() %}
							<a href="{{ url_for('main.edit_author', id=author.id) }}" class="btn btn-primary">Edit Author</a>
							<form action="{{ url_for('main.delete_author') }}" method="POST">
								{{ form.id(value=author.id) }}
								<input type="submit" class="btn btn-danger pull-right" value="Delete Author" />
							</form>
							{% endif %}
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
		{% else %}
			<h3 class="search-not-found">There's no authors yet.</h3>
		{% endif %}
	</div>
</div>
{% endblock %}
{% block scripts %}
{{ super() }}
<script type="text/javascript" src="{{ url_for('static', filename='js/author_search.js') }}"></script>
{% endblock %}

libr/templates/main/book-search-results.html
	{% if books %}
		<table class="table">
			<thead>
				<tr>
				<th>Book ID</th>
				<th>Title</th>
				</tr>
			</thead>
			<tbody>
				{% for book in books %}
					<tr>
						<td>{{ book.id }}</td>
						<td><a href="{{ url_for('main.book_detail', id=book.id) }}">{{ book.title }}</a></td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	{% else %}
		<h3 class="search-not-found">Can't find anything.</h3>
	{% endif %}

libr/templates/main/book_detail.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}Book Detail{% endblock %}
{% block main_content %}
<div class="container">
	<div class="page-header">
		<h1>About Book - "{{ book.title }}"</h1>
	</div>
	<p>
		<b>Book ID:</b> {{ book.id }}
	</p>
	<p>
		<b>Title:</b> "{{ book.title }}"
	</p>
	<p><b>Author(s):</b></p>
	{% if book.authors %}
	<ul>
		{% for author in book.authors %}
				<li><a href="{{ url_for('main.author_detail', id=author.id) }}">{{ author.name }}</a></li>
		{% endfor %}
	</ul>
	{% else %}
		<span>Sorry, "{{ book.title }}" doesn't have any specified authors yet.</span>
	{% endif %}
	{% if current_user.is_authenticated() %}
	<p>
		<a href="{{ url_for('main.edit_book', id=book.id) }}" class="btn btn-primary">Edit Book</a>
	</p>
	<form action="{{ url_for('main.delete_book') }}" method="POST">
		{{ form.id(value=book.id) }}
		<input type="submit" class="btn btn-danger pull-right" value="Delete Book" />
	</form>
	{% endif %}
</div>
{% endblock %}

libr/templates/main/books.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}Books{% endblock %}
{% block main_content %}
<div class="container">
	<div class="page-header">
		<h1>Books</h1>
	</div>
	<div class="pull-left">
		<label class="label label-info" for="search-input">Input part of book title or author's name</label>
    	<input type="text" class="input-medium search-query" id="search-input">
    	<div class="btn btn-success" id="search-button">Find Book</div>
    	<div id="back-div"></div>
	</div>
	{% if current_user.is_authenticated() %}
	<a href="{{ url_for('main.add_book') }}" class="pull-right btn btn-warning">Add new book entry</a>
	{% endif %}
	<div class="result-table clearfix">
		{% if books %}
		<table class="table">
			<thead>
				<tr>
				<th>Book ID</th>
				<th>Title</th>
				<th>More</th>
				</tr>
			</thead>
			<tbody>
				{% for book in books %}
					<tr>
						<td>{{ book.id }}</td>
						<td>{{ book.title }}</td>
						<td>
							<a href="{{ url_for('main.book_detail', id=book.id) }}" class="btn btn-info">About Book</a>
							{% if current_user.is_authenticated() %}  
							<a href="{{ url_for('main.edit_book', id=book.id) }}" class="btn btn-primary">Edit Book</a> 
							<form action="{{ url_for('main.delete_book') }}" method="POST">
								{{ form.id(value=book.id) }}
								<input type="submit" class="btn btn-danger pull-right" value="Delete Book" />
							</form>
							{% endif %}
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
		{% else %}
			<h3 class="search-not-found">There's no books yet.</h3>
		{% endif %}
	</div>
</div>
{% endblock %}
{% block scripts %}
{{ super() }}
<script type="text/javascript" src="{{ url_for('static', filename='js/book_search.js') }}"></script>
{% endblock %}

libr/templates/main/edit_author.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}Edit Author{% endblock %}
{% block main_content %}
<div class="container">
	<div class="page-header">
		<h1>Edit Author</h1>
	</div>
	<div class="col-md-4">
		{{ wtf.quick_form(form) }}
	</div>
	<a href="{{ url_for('main.add_book', next=url_for('main.edit_author', id=author.id)) }}" class="btn add-object"><span class="glyphicon glyphicon-plus"></span> Add Book</a>
</div>
{% endblock %}

libr/templates/main/edit_book.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}Edit Book{% endblock %}
{% block main_content %}
<div class="container">
	<div class="page-header">
		<h1>Edit Book</h1>
	</div>
	<div class="col-md-4">
		{{ wtf.quick_form(form) }}
	</div>
	<a href="{{ url_for('main.add_author', next=url_for('main.edit_book', id=book.id)) }}" class="btn add-object"><span class="glyphicon glyphicon-plus"></span> Add Author</a>
</div>
{% endblock %}